freeze_param: [
    "encoder.encoders.mask_emb", "encoder.encoders.feature_extractor",
    "encoder.encoders.post_extract_proj", "encoder.encoders.quantizer",
    "encoder.encoders.project_q", "encoder.encoders.encoder.pos_conv",
]

input_size: 2048
encoder: wav2vec2
encoder_conf:
    output_size: 768
    normalize_before: true
    freeze_finetune_updates: 5000
    w2v_url: https://huggingface.co/kehanlu/mandarin-wav2vec2-fairseq/resolve/main/mandarin_wav2vec2_fairseq.pt
    w2v_dir_path: ./downloads/wav2vec_pretrained_models/mandarin_wav2vec2_fairseq.pt

decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 0
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

model_conf:
    ctc_weight: 1.0
    lsm_weight: 0.1
    length_normalized_loss: false

# minibatch related
batch_type: folded
batch_size: 32

# optimization related
accum_grad: 2
grad_clip: 5
patience: 3
max_epoch: 30
val_scheduler_criterion:
    - valid
    - acc
best_model_criterion:
-   - valid
    - cer_ctc
    - min
early_stopping_criterion:
    - valid
    - cer_ctc
    - min    
keep_nbest_models: 10

optim: adam
optim_conf:
    lr: 0.0001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000

unused_parameters: true

frontend: null

normalize: null

specaug: null
